# Generated by Django 4.2 on 2024-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_ad_image_seller_review_dispute_alter_ad_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
